# Generated by Django 5.1.1 on 2024-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('weight_pounds', models.FloatField()),
                ('karat', models.FloatField()),
                ('amount_gold', models.FloatField()),
            ],
        ),
    ]
